---
# tasks file for launch_aws_vpc
- name: Create vpc {{ ec2_name_prefix }}-vpc
  ec2_vpc_net:
    name: "{{ ec2_name_prefix }}-vpc"
    cidr_block: "{{ ec2_cidr_prefix[ec2_name_prefix] }}.0.0/16"
    region: "{{ ec2_region }}"
  register: create_vpc
  until: create_vpc is not failed
  retries: 5

- name: Set security group rules template
  set_fact:
    from_template: "{{ lookup('template', 'vpc_rules.j2') }}"

- name: Create security group {{ ec2_name_prefix }}-Public-SG
  ec2_group:
    name: "{{ ec2_name_prefix }}-Public-SG"
    description: "{{ ec2_name_prefix }}-Public-SG"
    vpc_id: "{{ create_vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    rules: "{{ from_template.all_rules }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_vpc_id is undefined
  register: create_sg
  until: create_sg is not failed
  retries: 5

- name: Create subnet {{ ec2_name_prefix }}-Public-A
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    az: "{{ ec2_az }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    cidr: "{{ ec2_cidr_prefix[ec2_name_prefix] }}.0.0/24"
    wait_timeout: 600
    map_public: yes
    resource_tags:
      Name: "{{ ec2_name_prefix }}-Public-A"
  register: create_subnet
  when: ec2_vpc_id is undefined
  until: create_subnet is not failed
  retries: 5

- debug:
    msg: "{{ create_subnet }}"

- name: Get subnet ids
  set_fact:
    subnet_id: "{{ create_subnet.subnet.id }}"
#    subnet_ids: "{{ create_subnet
#      | selectattr('subnet.id', 'defined')
#      | map(attribute='subnet.id')
#      | list
#      | unique }}"

- name: Create igw {{ ec2_name_prefix }}-Gateway
  ec2_vpc_igw:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    tags:
      Name: "{{ ec2_name_prefix }}-Gateway"
      Demonstration: "{{ ec2_name_prefix }}"
  register: create_igw
  until: create_igw is not failed
  retries: 15
  when: ec2_vpc_id is undefined

- name: Create rtb {{ ec2_name_prefix }}-RouteTable
  ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    subnets: "{{ subnet_ids }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ create_igw.gateway_id }}"
    tags:
      Name: "{{ ec2_name_prefix }}-RouteTable"
  register: create_rtb
  until: create_rtb is not failed
  retries: 5
  when: ec2_vpc_id is undefined
